//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.35312
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechZone_ModPack_Launcher_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MechZone_ModPack_Launcher_v2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Config Files ähnelt.
        /// </summary>
        internal static string DownloadForm_UnzipMods_Backup_Config_Files {
            get {
                return ResourceManager.GetString("DownloadForm_UnzipMods_Backup_Config_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to Backup your Config Files? ähnelt.
        /// </summary>
        internal static string DownloadForm_UnzipMods_Do_you_want_to_Backup_your_Config_Files_ {
            get {
                return ResourceManager.GetString("DownloadForm_UnzipMods_Do_you_want_to_Backup_your_Config_Files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///{1} ähnelt.
        /// </summary>
        internal static string Exception_Output {
            get {
                return ResourceManager.GetString("Exception_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten, bitte versuche es noch einmal. ähnelt.
        /// </summary>
        internal static string MainWindow_addProfile_Click_Es_ist_ein_Fehler_aufgetreten__bitte_versuche_es_noch_einmal_ {
            get {
                return ResourceManager.GetString("MainWindow_addProfile_Click_Es_ist_ein_Fehler_aufgetreten__bitte_versuche_es_noch" +
                        "_einmal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entweder ist der Server nicht erreichbar oder
        ///dein Passwort oder Benutzername stimmt nicht! ähnelt.
        /// </summary>
        internal static string MainWindow_Authenticate_ {
            get {
                return ResourceManager.GetString("MainWindow_Authenticate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MainWindow_Authenticate_Error {
            get {
                return ResourceManager.GetString("MainWindow_Authenticate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Modpack update available!
        ///Do you want to update? ähnelt.
        /// </summary>
        internal static string MainWindow_LaunchModPack_ {
            get {
                return ResourceManager.GetString("MainWindow_LaunchModPack_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Update Available ähnelt.
        /// </summary>
        internal static string MainWindow_LaunchModPack_New_Update_Available {
            get {
                return ResourceManager.GetString("MainWindow_LaunchModPack_New_Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap space {
            get {
                object obj = ResourceManager.GetObject("space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon taskbarIcon {
            get {
                object obj = ResourceManager.GetObject("taskbarIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
